# Generated by Django 5.1.2 on 2024-10-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemake')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_vin', models.CharField(max_length=30, unique=True, verbose_name='chassis/vin')),
                ('plate', models.CharField(max_length=6)),
                ('insurance', models.DateField()),
                ('owner', models.ManyToManyField(to='owners.owner')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemodel')),
            ],
        ),
    ]
