# Generated by Django 5.1.2 on 2024-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemake',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
