# Generated by Django 5.1.2 on 2024-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='TX', max_length=6),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year',
            field=models.CharField(default=2000, max_length=4),
        ),
    ]
