# Generated by Django 5.1.2 on 2024-10-25 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_plate_alter_vehiclemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
