# Generated by Django 5.1.2 on 2024-10-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='plate',
        ),
    ]
