# Generated by Django 5.1.2 on 2024-10-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_plate_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='plate',
            field=models.CharField(max_length=6),
        ),
    ]
