# Generated by Django 5.1.2 on 2024-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
