# Generated by Django 5.1.2 on 2024-10-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_alter_owner_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='state',
        ),
    ]
