# Generated by Django 5.1.2 on 2024-10-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_remove_owner_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='phone2',
            new_name='phone1',
        ),
    ]
