# Generated by Django 5.1.2 on 2024-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_rename_phone2_owner_phone1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='owner',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
