# Generated by Django 5.1.2 on 2024-10-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_alter_owner_email_alter_owner_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='is_business',
        ),
    ]
